### PR TITLE
Make minikube ver configurable; bump default to 1.2.0

### PR DESCRIPTION
**Pull request by mmazur**

### CODE REVIEW

**Comment by fabiand** [comment]
@mmazur can you rebase this then I can merge it

**Comment by mmazur** [comment]
Done

**Comment by fabiand** [comment]
Actually - what is the reason for this PR?

I tlooks like you want ot make the minikube ver configurable, but was trhis only because minikube was outdated - or another reason?

**Comment by mmazur** [comment]
Our CI testing revealed that kubevirt+minikube is quite unstable[1] (at least on travis). Whenever I tried getting a little bit closer to the source of the issue, first thing to do was to use latest minikube. Merging this patch will make it easier to do the debugging on next attempt.

[1] https://github.com/kubevirt/ansible-kubevirt-modules/issues/240#issuecomment-505825947

**Comment by fabiand** [comment]
Hm. Ok.

For the demo it is quite stable.

**Comment by mmazur** [comment]
We have very repeatable instability and it's either the cluster or kubevirt/cdi. I was hoping to slowly debug this over time, hence this patch.

**Comment by mmazur** [comment]
@fabiand ping, please merge

**Pull request closed without merging**
