### PR TITLE
increase timeout for pods, fix missing param for virtctl

### PR DESCRIPTION
**Pull request by ksimon1**
Removed timeout for waiting on infrastructure pods because Travis test fails in common templates.
Fixed missing version param for virtctl (Download fails, because it uses non existing URL)

### CODE REVIEW

**Comment by ksimon1** [comment]
https://travis-ci.org/kubevirt/common-templates/jobs/477829590

**Comment by MarSik** [comment]
@fabiand Notice the following in the log @ksimon1 [referenced](https://travis-ci.org/kubevirt/common-templates/jobs/477829590#L838):

There is a missing path segment where version should be when downloading virtctl:
```
_cache virtctl 'curl -Lo virtctl     https://github.com/kubevirt/kubevirt/releases/download//virtctl--linux-amd64'
```

I can only guess about the timeout, but I think @ksimon1 saw that during testing. The downloads from Travis can be sometimes pretty slow.

**Comment by fabiand** [comment]
Why is there a missing path segment?

**Comment by ksimon1** [comment]
previously the code passed 2 params, now it passes only one, so the version param is missing. https://github.com/fabiand/traviskube/commit/ae58dcd4f67ebf0f589ea3ec8938c32188e428ea#diff-055760deab7fd8158deef733b100be18R113

**Comment by fabiand** [comment]
Thanks to CI.

**Pull request merged**
